# src/main/resources/api/openapi.yaml
openapi: 3.0.3
info:
  title: Bookstore EC API
  version: 1.0.0
paths:
  /books/{bookId}:
    get:
      summary: Get a book by ID
      operationId: getBookById
      tags:
        - books
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: book not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        author:
          type: string
